import { type PaletteColor, type Theme } from '@mui/material';
import { type ReactNode } from 'react';

import { useTheme } from '~/helpers';

export interface LoadingProps {
  color?: keyof Theme['palette'];
  margin?: 'auto' | 'none';
  size?: number;
}

export function Loading({
  color = 'primary',
  margin = 'auto',
  size = 156,
}: LoadingProps): ReactNode {
  const { palette } = useTheme();
  const actualColor = (palette[color] as PaletteColor)?.main ?? color;

  return (
    // <!-- [ldio] generated by https://loading.io/ -->
    <svg
      style={{
        display: 'block',
        shapeRendering: 'auto',
        margin: margin === 'none' ? 0 : 'auto',
        background: 'none',
      }}
      height={`${size}px`}
      width={`${size}px`}
      preserveAspectRatio="xMidYMid"
      viewBox="0 0 100 100"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g transform="translate(50,50)">
        <g transform="scale(0.88)">
          <circle cx="0" cy="0" r="50" fill={actualColor}></circle>
          <circle cx="0" cy="-29" r="12" fill="#ffffff" transform="rotate(279.406)">
            <animateTransform
              attributeName="transform"
              type="rotate"
              dur="0.7575757575757576s"
              repeatCount="indefinite"
              keyTimes="0;1"
              values="0 0 0;360 0 0"
            ></animateTransform>
          </circle>
        </g>
      </g>
    </svg>
  );
}
